### ISSUE TITLE
Cannot read property 'getLastSelection' of undefined

### ISSUE THREAD

**Issue by despairblue** [abe33/minimap-highlight-selected#4]
## Repro Steps
1. disable auto toggle in minimap plugin
2. reload atom
3. click anywhere in a text file

```javascript
TypeError: Cannot read property 'getLastSelection' of undefined
  at FakeEditor.(anonymous function) [as getLastSelection] (/home/despairblue/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:17:53)
  at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.handleSelection (/home/despairblue/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:30:22)
  at MinimapHighlightSelectedView.handleSelection (/home/despairblue/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:31:7)
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/usr/share/atom/resources/app/src/text-editor-component.js:271:49)
  at CallbackQueue.mixInto.notifyAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (/usr/share/atom/resources/app/src/text-editor-component.js:619:14)
  at [object Object].boundMethod [as focused] (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.focused (/usr/share/atom/resources/app/src/text-editor-element.js:199:55)
```

**Comment by abe33** [comment]
Thanks for the report, I'll fix that asap
