### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getActiveTextEditor' of undefined

### ISSUE THREAD

**Issue by hatzopoulos** [abe33/minimap-highlight-selected#5]
[Enter steps to reproduce below:]

1. With the same packages installed,
2. Open a folder (project) in atom, with already opened tabs, 
3. while having the minimap panel in view,
4. switch to another file

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [minimap-highlight-selected](https://github.com/abe33/minimap-highlight-selected) package, v3.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getActiveTextEditor' of undefined

```
At /c:/Users/Entropy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:57

TypeError: Cannot read property 'getActiveTextEditor' of undefined
  at MinimapHighlightSelectedView.handleSelection (c:\Users\Entropy\.atom\packages\minimap-highlight-selected\lib\minimap-highlight-selected-view.coffee:29:21)
  at MinimapHighlightSelectedView.handleSelection (c:\Users\Entropy\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:1:1)
  at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (c:\Users\Entropy\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:29:6)
  at c:\Users\Entropy\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:13:8
  at Emitter.module.exports.Emitter.emit (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\src\pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:328:21)
  at tabs-tab.<anonymous> (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (c:\Users\Entropy\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "project-ring",
      "sublime-tabs",
      "revert-buffer",
      "highlight-line",
      "bezier-curve-editor",
      "figlet"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.5
color-picker, v1.4.4
file-icons, v1.4.8
hex, v0.5.0
highlight-column, v0.4.0
highlight-selected, v0.8.0
linter, v0.11.0
minimap, v3.5.6
minimap-color-highlight, v3.1.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v3.1.2
minimap-selection, v3.1.1
project-manager, v1.15.5
project-palette-finder, v2.4.10
Remote-FTP, v0.4.7
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Thanks for the report, I'll fix that asap.
